### PR TITLE
Feat/choropleth map

### PR DESCRIPTION
**Pull request by AlvinFok**
Map show the winner party color
Screenshot 2023-01-03 at 11 56 59 AM

### CODE REVIEW

**Comment by joejoe2** [comment]
How can we apply map to the legislator data ?

**Comment by joejoe2** [comment]
I made it compatible with legislator-at-large and add some todos in code. @AlvinFok please check it.

**Comment by AlvinFok** [comment]
OK. I will check it today

**Comment by AlvinFok** [comment]
I add the year selector plz check

**Comment by joejoe2** [comment]
Title should be changed (something like: majorities in Taiwan cities of 2016/2020 president election). And add legends to map to show which color represent which candidate.

**Comment by AlvinFok** [comment]
> 



> Title should be changed (something like: majorities in Taiwan cities of 2016/2020 president election). And add legends to map to show which color represent which candidate.

categorical choropleth seems unavailable with js plotly
https://github.com/plotly/plotly.js/issues/3468

**Comment by joejoe2** [comment]
legends added.

**Pull request merged**
