### PR TITLE
Feat/edu level

### PR DESCRIPTION
**Pull request by joejoe2**
count education levels of candidates/electees for each party
image
image

### CODE REVIEW

**Comment by AlvinFok** [comment]
I think a pie chart to show the ratio is also a good idea

**Comment by joejoe2** [comment]
I don't choose that because i want to see some differences between parties. For example, there are more bachelor candidates than master in 無黨籍.

**Comment by AlvinFok** [comment]
Maybe just for the elected candidate

**Comment by joejoe2** [comment]
add pie chart for edu level and gender

**Comment by AlvinFok** [comment]
Ok plz merge it

**Pull request merged**
