### PR TITLE
Parse legislator

### PR DESCRIPTION
**Pull request by joejoe2**
Do similar work in #1 , people vote for parties as candidates to elect the non-local legislators.

### CODE REVIEW

**Comment by joejoe2** [comment]
@AlvinFok How would you like to parse the local legislators ? Because each region has different candidates like below.
image

**Comment by AlvinFok** [comment]
So just replace the region code with the name

**Comment by joejoe2** [comment]
I am not very confident about parsing the local legislator data, please check it.

**Comment by AlvinFok** [comment]
Why you don't use the same parse file for 2016 and 2020?

**Comment by joejoe2** [comment]
Because the names of input files are not the same and I don't make it configurable. And there are also some small differences between their data formats (ex. some fields in 2020 having more digits than 2016)

**Comment by AlvinFok** [comment]
> @AlvinFok How would you like to parse the local legislators? Because each region has different candidates like below.
> image

So you already parse the local legislators' data correct?

**Comment by joejoe2** [comment]
Yeah, but i am not sure the format of parsed local legislator data is ok for you.

**Comment by AlvinFok** [comment]
Maybe we can make candidate.csv 2nd column from "嘉義市第01選區" to "第01選區".

**Comment by joejoe2** [comment]
OK, done.

**Comment by AlvinFok** [comment]
Ok plz merge the branch

**Pull request merged**
