### PR TITLE
parse president data

### PR DESCRIPTION
**Pull request by joejoe2**
I have parsed the 2020 president data at city and nation level. Do we have to check and parse the other data before visualization ?

### CODE REVIEW

**Comment by AlvinFok** [comment]
Please desire how do you clean up the data and add comments in the py file

**Comment by joejoe2** [comment]
run `python parser.py` in `./dataset/voteData/2020總統立委/總統` will generate parsed data at `./dataset/voteData/cleaned/president/2020/`

**Comment by AlvinFok** [comment]
> 

I mean what kind of value you change or delete

**Comment by joejoe2** [comment]
image
replace the first 6 cols with city name and change 7-th col from candidate code to candidate name

**Comment by AlvinFok** [comment]
Can you do the same thing on elcand.csv?

**Comment by joejoe2** [comment]
image
what are want to parse ?

**Comment by AlvinFok** [comment]
Col1-5, 8. I think that all we need to parse with elcand.csv.

**Comment by joejoe2** [comment]
Col1-5 in  elcand.csv is not meaningful because the president election is at national level, I wiil directly remove them.

**Comment by AlvinFok** [comment]
I don't prefer to remove any data because we need to export some exciting relationships. For example, we can say there are all female candidates in Taipei city.

**Comment by joejoe2** [comment]
Col1-5 in elcand.csv mean this is an president level election. The codes in there are empty values like "00","000","01","000","0000"

**Comment by AlvinFok** [comment]
Therefore, we can change the code from "00" to "台北" right?

**Comment by joejoe2** [comment]
No. All col1-5 of different candidates are "00","000","01","000","0000". This represent the election is held on the national level. You may want to use the `出生地` instead.

**Comment by joejoe2** [comment]
And the president data in 2012, 2008, ... have different format that isn't mentioned in spec, so I cannot parse it correctly.

**Comment by AlvinFok** [comment]
> No. All col1-5 of different candidates are "00","000","01","000","0000". This represent the election is held on the national level. You may want to use the `出生地` instead.

Oh, you are right.

**Comment by AlvinFok** [comment]
> And the president data in 2012, 2008, ... have different format that isn't mentioned in spec, so I cannot parse it correctly.

Is the format of Members of Legislative Yuan is same as president?

**Comment by joejoe2** [comment]
There are 2 types of legislator: legislator(local) and legislator-at-large(non-local). I haven't check their format. 

 The data before 2012 has different city/town/area code rule and is not mentioned in spec. It is difficult to parse it because we may have to search and hardcode all city/town name and their responding codes.

**Comment by AlvinFok** [comment]
Data after 2012 is enough.

**Review by AlvinFok — APPROVED** [review]

**Pull request merged**
